_wandb:
    value:
        cli_version: 0.23.0
        e:
            8kzcwadth98niceankpky0g1br9gfp8f:
                codePath: exploratory/pytorch-cnn-mnist/pytorch-cnn-mnist.py
                codePathLocal: exploratory/pytorch-cnn-mnist/pytorch-cnn-mnist.py
                cpu_count: 6
                cpu_count_logical: 6
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "124434268160"
                        used: "84470509568"
                email: ali.jahangiri@eit.lth.se
                executable: /bin/python
                git:
                    commit: 45a2dfc76c855e83d6128ea19147a61f1f1202b1
                gpu: Orin (nvgpu)
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      name: Orin (nvgpu)
                      uuid: 9b25f227-0772-5986-8a61-fb20f196f77b
                host: jetson-desktop
                memory:
                    total: "7990079488"
                os: Linux-5.15.148-tegra-aarch64-with-glibc2.35
                program: /home/jetson/Documents/github/EdgeFF/exploratory/pytorch-cnn-mnist/pytorch-cnn-mnist.py
                python: CPython 3.10.12
                root: /home/jetson/Documents/github/EdgeFF
                startedAt: "2025-11-23T16:38:54.256972Z"
                writerId: 8kzcwadth98niceankpky0g1br9gfp8f
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-aarch64
batch_size:
    value: 64
epochs:
    value: 10
log_interval:
    value: 10
lr:
    value: 0.01
momentum:
    value: 0.5
no_cuda:
    value: false
seed:
    value: 1
test_batch_size:
    value: 1000
