_wandb:
    value:
        cli_version: 0.23.0
        e:
            un7kk18eentoo0boqw5pqzjo42mdif2g:
                codePath: exploratory\pytorch-cnn-mnist\pytorch-cnn-mnist.py
                codePathLocal: exploratory\pytorch-cnn-mnist\pytorch-cnn-mnist.py
                cpu_count: 12
                cpu_count_logical: 14
                disk:
                    /:
                        total: "508625416192"
                        used: "371355832320"
                email: ali.jahangiri@eit.lth.se
                executable: C:\Users\user\Documents\GitHub\EdgeFF\.venv\Scripts\python.exe
                git:
                    commit: 8ee5f1aa11456d74a0b08e63ad1bf478d5e848bd
                    remote: https://github.com/aliphys/EdgeFF.git
                host: DESKTOP-28JEA7S
                memory:
                    total: "16597598208"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\user\Documents\GitHub\EdgeFF\exploratory\pytorch-cnn-mnist\pytorch-cnn-mnist.py
                python: CPython 3.13.5
                root: C:\Users\user\Documents\GitHub\EdgeFF
                startedAt: "2025-11-19T14:56:04.990259Z"
                writerId: un7kk18eentoo0boqw5pqzjo42mdif2g
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
            "4": 3.13.5
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 10
log_interval:
    value: 10
lr:
    value: 0.01
momentum:
    value: 0.5
no_cuda:
    value: false
seed:
    value: 1
test_batch_size:
    value: 1000
